/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.em.secretaria;

import static br.com.em.main.JfTelaLogin.usuario;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pablo
 */
public class JfTelaPrincipalSecretaria extends javax.swing.JFrame {

    JpCliente jpc = new JpCliente();
    JpProcesso jpp = new JpProcesso();
    JpAgenda jpa = new JpAgenda();
   JpAndamentoProcessual jpap = new JpAndamentoProcessual();

    /**
     * Creates new form TelaPrincipalSecretaria
     */
    public JfTelaPrincipalSecretaria() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbConsultarProcesso = new javax.swing.JButton();
        jbCadastrarProcesso = new javax.swing.JButton();
        jbCadastrarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbTrocarUsuario = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jbMinhaAgenda = new javax.swing.JButton();
        jbAndamentoProcesso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlusuario = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        jlhora = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlpPrincipal = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sitema Escritório Modelo - Secretária");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jbConsultarProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/processover.png"))); // NOI18N
        jbConsultarProcesso.setText("<html><p align=\"center\" >Consultar<br>Processo");
        jbConsultarProcesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConsultarProcesso.setEnabled(false);
        jbConsultarProcesso.setFocusPainted(false);
        jbConsultarProcesso.setFocusable(false);
        jbConsultarProcesso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbConsultarProcesso.setOpaque(false);
        jbConsultarProcesso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbConsultarProcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbConsultarProcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbConsultarProcessoMouseExited(evt);
            }
        });

        jbCadastrarProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/processo+.png"))); // NOI18N
        jbCadastrarProcesso.setText("<html><p align=\"center\" >Cadastrar<br>Processo");
        jbCadastrarProcesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastrarProcesso.setFocusPainted(false);
        jbCadastrarProcesso.setFocusable(false);
        jbCadastrarProcesso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCadastrarProcesso.setOpaque(false);
        jbCadastrarProcesso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCadastrarProcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCadastrarProcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCadastrarProcessoMouseExited(evt);
            }
        });
        jbCadastrarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarProcessoActionPerformed(evt);
            }
        });

        jbCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/client.png"))); // NOI18N
        jbCadastrarCliente.setText("<html><p align=\"center\" >Cadastrar<br>Cliente");
        jbCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastrarCliente.setFocusPainted(false);
        jbCadastrarCliente.setFocusable(false);
        jbCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCadastrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCadastrarClienteMouseExited(evt);
            }
        });
        jbCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarClienteActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/update.png"))); // NOI18N
        jbTrocarUsuario.setText("<html><p align=\"center\" >Trocar<br>Usuário");
        jbTrocarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbTrocarUsuario.setFocusPainted(false);
        jbTrocarUsuario.setFocusable(false);
        jbTrocarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbTrocarUsuario.setOpaque(false);
        jbTrocarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbTrocarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbTrocarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbTrocarUsuarioMouseExited(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/cancelar.png"))); // NOI18N
        jbSair.setText("<html><p align=\"center\" >Sair");
        jbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSair.setFocusPainted(false);
        jbSair.setFocusable(false);
        jbSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSair.setOpaque(false);
        jbSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSairMouseExited(evt);
            }
        });
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbMinhaAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/agenda.png"))); // NOI18N
        jbMinhaAgenda.setText("<html><p align=\"center\" >Minha<br>Agenda");
        jbMinhaAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMinhaAgenda.setFocusPainted(false);
        jbMinhaAgenda.setFocusable(false);
        jbMinhaAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMinhaAgenda.setOpaque(false);
        jbMinhaAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMinhaAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbMinhaAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbMinhaAgendaMouseExited(evt);
            }
        });
        jbMinhaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMinhaAgendaActionPerformed(evt);
            }
        });

        jbAndamentoProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/em/icons/and_process.png"))); // NOI18N
        jbAndamentoProcesso.setText("<html><p align=\"center\" >Andamento<br>Processual ");
        jbAndamentoProcesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAndamentoProcesso.setFocusPainted(false);
        jbAndamentoProcesso.setFocusable(false);
        jbAndamentoProcesso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAndamentoProcesso.setOpaque(false);
        jbAndamentoProcesso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAndamentoProcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAndamentoProcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAndamentoProcessoMouseExited(evt);
            }
        });
        jbAndamentoProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAndamentoProcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadastrarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsultarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAndamentoProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMinhaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                .addComponent(jbTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCadastrarCliente, jbCadastrarProcesso, jbConsultarProcesso});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbSair, jbTrocarUsuario});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2)
                    .addComponent(jbTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMinhaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAndamentoProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSeparator2, jSeparator4, jbCadastrarCliente, jbCadastrarProcesso, jbConsultarProcesso});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbSair, jbTrocarUsuario});

        jbConsultarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbConsultarProcesso.setBorder(null);
        jbConsultarProcesso.setOpaque(false);
        jbConsultarProcesso.setContentAreaFilled(false);
        jbConsultarProcesso.setBorderPainted(false);
        jbCadastrarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarProcesso.setBorder(null);
        jbCadastrarProcesso.setOpaque(false);
        jbCadastrarProcesso.setContentAreaFilled(false);
        jbCadastrarProcesso.setBorderPainted(false);
        jbCadastrarCliente.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarCliente.setBorder(null);
        jbCadastrarCliente.setOpaque(false);
        jbCadastrarCliente.setContentAreaFilled(false);
        jbCadastrarCliente.setBorderPainted(false);
        jbTrocarUsuario.setMargin(new Insets(0, 0, 0, 0));
        jbTrocarUsuario.setBorder(null);
        jbTrocarUsuario.setOpaque(false);
        jbTrocarUsuario.setContentAreaFilled(false);
        jbTrocarUsuario.setBorderPainted(false);
        jbSair.setMargin(new Insets(0, 0, 0, 0));
        jbSair.setBorder(null);
        jbSair.setOpaque(false);
        jbSair.setContentAreaFilled(false);
        jbSair.setBorderPainted(false);
        jbMinhaAgenda.setMargin(new Insets(0, 0, 0, 0));
        jbMinhaAgenda.setBorder(null);
        jbMinhaAgenda.setOpaque(false);
        jbMinhaAgenda.setContentAreaFilled(false);
        jbMinhaAgenda.setBorderPainted(false);
        jbAndamentoProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbAndamentoProcesso.setBorder(null);
        jbAndamentoProcesso.setOpaque(false);
        jbAndamentoProcesso.setContentAreaFilled(false);
        jbAndamentoProcesso.setBorderPainted(false);

        jlusuario.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jlusuario.setText("usuario");

        jldata.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jldata.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jldata.setText("data");

        jlhora.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jlhora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlhora.setText("hora");
        jlhora.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jlhora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 724, Short.MAX_VALUE)
                .addComponent(jldata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlhora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlhora)
                        .addComponent(jlusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jldata, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpPrincipal.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jlpPrincipalLayout = new javax.swing.GroupLayout(jlpPrincipal);
        jlpPrincipal.setLayout(jlpPrincipalLayout);
        jlpPrincipalLayout.setHorizontalGroup(
            jlpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jlpPrincipalLayout.setVerticalGroup(
            jlpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1076, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarClienteActionPerformed

        jpc.setBounds(0, 0, 1030, 460);
        jlpPrincipal.removeAll();
        jlpPrincipal.add(jpc, new Integer(0), 0);
        jlpPrincipal.moveToFront(jpc);
    }//GEN-LAST:event_jbCadastrarClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        URL url = getClass().getResource("/br/com/em/icons/advogado.png");
        ImageIcon imgicon = new ImageIcon(url);
        this.setIconImage(imgicon.getImage());

        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.DEFAULT);
        jldata.setText(formatador.format(data));
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
        jlusuario.setText(usuario);
    }//GEN-LAST:event_formWindowActivated

    private void jbCadastrarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarProcessoActionPerformed

        jpp.setBounds(0, 0, 1030, 460);
        jlpPrincipal.removeAll();
        jlpPrincipal.add(jpp, new Integer(0), 0);
        jlpPrincipal.moveToFront(jpp);
    }//GEN-LAST:event_jbCadastrarProcessoActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbMinhaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMinhaAgendaActionPerformed
        jpa.setBounds(0, 0, 1030, 460);
        jlpPrincipal.removeAll();
        jlpPrincipal.add(jpa, new Integer(0), 0);
        jlpPrincipal.moveToFront(jpa);
    }//GEN-LAST:event_jbMinhaAgendaActionPerformed

    private void jbCadastrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarClienteMouseEntered
        jbCadastrarCliente.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarCliente.setBorder(null);
        jbCadastrarCliente.setOpaque(true);
        jbCadastrarCliente.setContentAreaFilled(true);
        jbCadastrarCliente.setBorderPainted(true);
    }//GEN-LAST:event_jbCadastrarClienteMouseEntered

    private void jbCadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarClienteMouseExited
        jbCadastrarCliente.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarCliente.setBorder(null);
        jbCadastrarCliente.setOpaque(false);
        jbCadastrarCliente.setContentAreaFilled(false);
        jbCadastrarCliente.setBorderPainted(false);
    }//GEN-LAST:event_jbCadastrarClienteMouseExited

    private void jbCadastrarProcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarProcessoMouseEntered
        jbCadastrarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarProcesso.setBorder(null);
        jbCadastrarProcesso.setOpaque(true);
        jbCadastrarProcesso.setContentAreaFilled(true);
        jbCadastrarProcesso.setBorderPainted(true);
    }//GEN-LAST:event_jbCadastrarProcessoMouseEntered

    private void jbCadastrarProcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarProcessoMouseExited
        jbCadastrarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbCadastrarProcesso.setBorder(null);
        jbCadastrarProcesso.setOpaque(false);
        jbCadastrarProcesso.setContentAreaFilled(false);
        jbCadastrarProcesso.setBorderPainted(false);
    }//GEN-LAST:event_jbCadastrarProcessoMouseExited

    private void jbConsultarProcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbConsultarProcessoMouseEntered
        jbConsultarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbConsultarProcesso.setBorder(null);
        jbConsultarProcesso.setOpaque(true);
        jbConsultarProcesso.setContentAreaFilled(true);
        jbConsultarProcesso.setBorderPainted(true);
    }//GEN-LAST:event_jbConsultarProcessoMouseEntered

    private void jbConsultarProcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbConsultarProcessoMouseExited
        jbConsultarProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbConsultarProcesso.setBorder(null);
        jbConsultarProcesso.setOpaque(false);
        jbConsultarProcesso.setContentAreaFilled(false);
        jbConsultarProcesso.setBorderPainted(false);
    }//GEN-LAST:event_jbConsultarProcessoMouseExited

    private void jbMinhaAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMinhaAgendaMouseEntered
        jbMinhaAgenda.setMargin(new Insets(0, 0, 0, 0));
        jbMinhaAgenda.setBorder(null);
        jbMinhaAgenda.setOpaque(true);
        jbMinhaAgenda.setContentAreaFilled(true);
        jbMinhaAgenda.setBorderPainted(true);
    }//GEN-LAST:event_jbMinhaAgendaMouseEntered

    private void jbMinhaAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMinhaAgendaMouseExited
        jbMinhaAgenda.setMargin(new Insets(0, 0, 0, 0));
        jbMinhaAgenda.setBorder(null);
        jbMinhaAgenda.setOpaque(false);
        jbMinhaAgenda.setContentAreaFilled(false);
        jbMinhaAgenda.setBorderPainted(false);
    }//GEN-LAST:event_jbMinhaAgendaMouseExited

    private void jbTrocarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTrocarUsuarioMouseEntered
        jbTrocarUsuario.setMargin(new Insets(0, 0, 0, 0));
        jbTrocarUsuario.setBorder(null);
        jbTrocarUsuario.setOpaque(true);
        jbTrocarUsuario.setContentAreaFilled(true);
        jbTrocarUsuario.setBorderPainted(true);
    }//GEN-LAST:event_jbTrocarUsuarioMouseEntered

    private void jbTrocarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTrocarUsuarioMouseExited
        jbTrocarUsuario.setMargin(new Insets(0, 0, 0, 0));
        jbTrocarUsuario.setBorder(null);
        jbTrocarUsuario.setOpaque(false);
        jbTrocarUsuario.setContentAreaFilled(false);
        jbTrocarUsuario.setBorderPainted(false);
    }//GEN-LAST:event_jbTrocarUsuarioMouseExited

    private void jbSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseEntered
        jbSair.setMargin(new Insets(0, 0, 0, 0));
        jbSair.setBorder(null);
        jbSair.setOpaque(true);
        jbSair.setContentAreaFilled(true);
        jbSair.setBorderPainted(true);
    }//GEN-LAST:event_jbSairMouseEntered

    private void jbSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseExited
        jbSair.setMargin(new Insets(0, 0, 0, 0));
        jbSair.setBorder(null);
        jbSair.setOpaque(false);
        jbSair.setContentAreaFilled(false);
        jbSair.setBorderPainted(false);
    }//GEN-LAST:event_jbSairMouseExited

    private void jbAndamentoProcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAndamentoProcessoMouseEntered
        jbAndamentoProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbAndamentoProcesso.setBorder(null);
        jbAndamentoProcesso.setOpaque(true);
        jbAndamentoProcesso.setContentAreaFilled(true);
        jbAndamentoProcesso.setBorderPainted(true);
    }//GEN-LAST:event_jbAndamentoProcessoMouseEntered

    private void jbAndamentoProcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAndamentoProcessoMouseExited
        jbAndamentoProcesso.setMargin(new Insets(0, 0, 0, 0));
        jbAndamentoProcesso.setBorder(null);
        jbAndamentoProcesso.setOpaque(false);
        jbAndamentoProcesso.setContentAreaFilled(false);
        jbAndamentoProcesso.setBorderPainted(false);
    }//GEN-LAST:event_jbAndamentoProcessoMouseExited

    private void jbAndamentoProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAndamentoProcessoActionPerformed
        jpap.setBounds(0, 0, 1030, 460);
        jlpPrincipal.removeAll();
        jlpPrincipal.add(jpap, new Integer(0), 0);
        jlpPrincipal.moveToFront(jpap);
    }//GEN-LAST:event_jbAndamentoProcessoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbAndamentoProcesso;
    private javax.swing.JButton jbCadastrarCliente;
    private javax.swing.JButton jbCadastrarProcesso;
    private javax.swing.JButton jbConsultarProcesso;
    private javax.swing.JButton jbMinhaAgenda;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbTrocarUsuario;
    private javax.swing.JLabel jldata;
    public static javax.swing.JLabel jlhora;
    private javax.swing.JLayeredPane jlpPrincipal;
    private javax.swing.JLabel jlusuario;
    // End of variables declaration//GEN-END:variables
}

class hora implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
        Calendar now = Calendar.getInstance();

        JfTelaPrincipalSecretaria.jlhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }

}
